# Generated by Django 2.2.1 on 2020-01-15 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='testFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('zipFile', models.FileField(upload_to='files/%Y/%m/%d')),
                ('unzipFile', models.CharField(max_length=250)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(default=0)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptName', models.CharField(max_length=50)),
                ('runTimes', models.IntegerField()),
                ('passTimes', models.IntegerField()),
                ('failTimes', models.IntegerField()),
                ('status', models.CharField(choices=[(0, 'start'), (1, 'running'), (2, 'complete')], max_length=2)),
                ('lastRunResult', models.BooleanField(default=0)),
                ('lastRunTime', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('testFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestScripts.testFile', verbose_name='testFile')),
            ],
        ),
        migrations.CreateModel(
            name='testReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runResult', models.BooleanField(default=0)),
                ('reportName', models.CharField(max_length=50)),
                ('reportFile', models.CharField(max_length=250)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('testScript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestScripts.testScript', verbose_name='testScript')),
            ],
        ),
    ]
