# Generated by Django 2.2.1 on 2020-01-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestScripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='isDelete',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='runResult',
            field=models.BooleanField(choices=[(0, 'pass'), (1, 'fail')], default=0),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='lastRunResult',
            field=models.BooleanField(choices=[(0, 'pass'), (1, 'fail')], default=0),
        ),
    ]
