# Generated by Django 2.2.1 on 2020-01-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestScripts', '0002_auto_20200115_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfile',
            name='isDelete',
            field=models.BooleanField(choices=[(0, 'undelete'), (1, 'delete')], default=0),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='unzipFile',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='isDelete',
            field=models.BooleanField(choices=[(0, 'undelete'), (1, 'delete')], default=0),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='failTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='isDelete',
            field=models.BooleanField(choices=[(0, 'undelete'), (1, 'delete')], default=0),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='passTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='runTimes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testscript',
            name='status',
            field=models.CharField(default='wait', max_length=20),
        ),
    ]
