# Generated by Django 2.2.1 on 2020-01-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestScripts', '0003_auto_20200115_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscript',
            name='scriptFile',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='testfile',
            name='zipFile',
            field=models.FileField(upload_to='zipfiles/%Y/%m/%d'),
        ),
    ]
