# Generated by Django 2.2.1 on 2020-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestScripts', '0004_auto_20200116_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='reportZip',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='reportFile',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='reportName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
