# Generated by Django 2.2.1 on 2020-01-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestScripts', '0005_auto_20200116_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='runResult',
        ),
        migrations.RemoveField(
            model_name='testscript',
            name='failTimes',
        ),
        migrations.RemoveField(
            model_name='testscript',
            name='lastRunResult',
        ),
        migrations.RemoveField(
            model_name='testscript',
            name='passTimes',
        ),
    ]
