# Generated by Django 2.2.1 on 2020-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestScripts', '0006_auto_20200116_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='testSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suiteName', models.CharField(max_length=50)),
                ('runTimes', models.IntegerField(default=0)),
                ('status', models.CharField(default='wait', max_length=20)),
                ('lastRunTime', models.DateTimeField(auto_now=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.BooleanField(choices=[(0, 'undelete'), (1, 'delete')], default=0)),
                ('testScript', models.ManyToManyField(to='TestScripts.testScript')),
            ],
        ),
    ]
